# This file was automatically generated by Umple from the following model:
# class Foo {}
# class Bar {
#   1 -- * Foo;
# }

# %% NEW FILE Bar BEGINS HERE %%

#PLEASE DO NOT EDIT THIS CODE
#This code was generated using the UMPLE 1.35.0.7523.c616a4dce modeling language!
# line 3 "model.ump"
# line 15 "model.ump"

class Bar():
    #------------------------
    # MEMBER VARIABLES
    #------------------------
    #Bar Associations
    #------------------------
    # CONSTRUCTOR
    #------------------------
    def __init__(self):
        self._foos = None
        self._foos = []

    #------------------------
    # INTERFACE
    #------------------------
    # Code from template association_GetMany
    def getFoo(self, index):
        aFoo = self._foos[index]
        return aFoo

    def getFoos(self):
        newFoos = tuple(self._foos)
        return newFoos

    def numberOfFoos(self):
        number = len(self._foos)
        return number

    def hasFoos(self):
        has = len(self._foos) > 0
        return has

    def indexOfFoo(self, aFoo):
        index = (-1 if not aFoo in self._foos else self._foos.index(aFoo))
        return index

    # Code from template association_MinimumNumberOfMethod
    @staticmethod
    def minimumNumberOfFoos():
        return 0

    # Code from template association_AddManyToOne
    def addFoo1(self):
        from Foo import Foo
        return Foo(self)

    def addFoo2(self, aFoo):
        wasAdded = False
        if (aFoo) in self._foos :
            return False
        existingBar = aFoo.getBar()
        isNewBar = not (existingBar is None) and not self == existingBar
        if isNewBar :
            aFoo.setBar(self)
        else :
            self._foos.append(aFoo)
        wasAdded = True
        return wasAdded

    def removeFoo(self, aFoo):
        wasRemoved = False
        #Unable to remove aFoo, as it must always have a bar
        if not self == aFoo.getBar() :
            self._foos.remove(aFoo)
            wasRemoved = True
        return wasRemoved

    # Code from template association_AddIndexControlFunctions
    def addFooAt(self, aFoo, index):
        wasAdded = False
        if self.addFoo(aFoo) :
            if index < 0 :
                index = 0
            if index > self.numberOfFoos() :
                index = self.numberOfFoos() - 1
            self._foos.remove(aFoo)
            self._foos.insert(index, aFoo)
            wasAdded = True
        return wasAdded

    def addOrMoveFooAt(self, aFoo, index):
        wasAdded = False
        if (aFoo) in self._foos :
            if index < 0 :
                index = 0
            if index > self.numberOfFoos() :
                index = self.numberOfFoos() - 1
            self._foos.remove(aFoo)
            self._foos.insert(index, aFoo)
            wasAdded = True
        else :
            wasAdded = self.addFooAt(aFoo, index)
        return wasAdded

    def delete(self):
        i = len(self._foos)
        while i > 0 :
            aFoo = self._foos[i - 1]
            aFoo.delete()
            i -= 1

    def addFoo(self, *argv):
        from Foo import Foo
        if len(argv) == 0 :
            return self.addFoo1()
        if len(argv) == 1 and isinstance(argv[0], Foo) :
            return self.addFoo2(argv[0])
        raise TypeError("No method matches provided parameters")





# %% NEW FILE Foo BEGINS HERE %%

#PLEASE DO NOT EDIT THIS CODE
#This code was generated using the UMPLE 1.35.0.7523.c616a4dce modeling language!
# line 2 "model.ump"
# line 10 "model.ump"

class Foo():
    #------------------------
    # MEMBER VARIABLES
    #------------------------
    #Foo Associations
    #------------------------
    # CONSTRUCTOR
    #------------------------
    def __init__(self, aBar):
        self._bar = None
        didAddBar = self.setBar(aBar)
        if not didAddBar :
            raise RuntimeError ("Unable to create foo due to bar. See https://manual.umple.org?RE002ViolationofAssociationMultiplicity.html")

    #------------------------
    # INTERFACE
    #------------------------
    # Code from template association_GetOne
    def getBar(self):
        return self._bar

    # Code from template association_SetOneToMany
    def setBar(self, aBar):
        wasSet = False
        if aBar is None :
            return wasSet
        existingBar = self._bar
        self._bar = aBar
        if not (existingBar is None) and not existingBar == aBar :
            existingBar.removeFoo(self)
        self._bar.addFoo(self)
        wasSet = True
        return wasSet

    def delete(self):
        placeholderBar = self._bar
        self._bar = None
        if not (placeholderBar is None) :
            placeholderBar.removeFoo(self)