import os
import re
import sys

# Match Umple file markers
UMPLE_FILE_MARKER_PATTERN = re.compile(r"# %% NEW FILE (.+?) BEGINS HERE %%")

# Match Python import statements
PYTHON_IMPORT_PATTERN = re.compile(r"^\s*from\s+([A-Z]\w*)\s+import\s+")


def save_file(output_dir: str, filename: str, content: list[str]) -> None:
    """
    Save content to a file in the specified output directory.
    :param output_dir: the base directory
    :param filename: the specific file name
    :param content: the content to write into the file. Each item in the list is a line.
    """
    output_path = os.path.join(output_dir, filename)

    # sanitize the content, removing newlines from the end of the file
    while content and content[-1].strip() == "":
        content.pop()

    # do the file writing
    with open(output_path, "w", encoding="utf-8") as out_f:
        out_f.writelines(content)

    print(f"Created file: {filename}")


def write_init_py(output_dir: str, filenames: list[str]) -> None:
    """
    Given the list of files within the module, write an __init__.py file that imports everything from each file.
    :param output_dir: the base directory
    :param filenames: list of filenames (without the .py extension)
    """
    content = []

    # add an import for each file to export everything
    for filename in filenames:
        content.append(f"from .{filename} import *\n")

    save_file(output_dir, "__init__.py", content)


def split_umple_python_source_file(input_file: str, output_dir: str):
    """
    By defaults, Umple generates a single Python file containing all classes and expects the user to manage the file splitting.
    This function splits the Python source code generated by Umple into a working module.
    :param input_file: the input source code file generated by Umple
    :param output_dir: the output directory where the module files will be created
    :return:
    """
    # ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)

    filenames: list[str] = []
    current_file: str = ""
    current_content: list[str] = []

    with open(input_file, "r", encoding="utf-8") as f:
        for line in f:
            match_marker = UMPLE_FILE_MARKER_PATTERN.match(line.strip())
            if match_marker:  # a new file begins
                # save previous file
                if current_file:
                    save_file(output_dir, current_file, current_content)

                # start a new file
                current_file = match_marker.group(1).strip()
                filenames.append(current_file)  # store file name for __init__.py

                current_file += ".py"

                # Reset and start new content with marker itself
                current_content = [line]
            else:  # regular line within the same file
                # Umple currently defaults to generate absolute import statements, which is more difficult to manage in a dataset.
                # therefore, we want to convert them to relative imports (by not providing namespace to Umple and adding a . in front of the module name)
                match_import = PYTHON_IMPORT_PATTERN.match(line)

                if match_import:
                    module = match_import.group(1)
                    line = line.replace(f"from {module} ", f"from .{module} ")

                current_content.append(line)

    # save the last file
    if current_file:
        save_file(output_dir, current_file, current_content)

    # write __init__.py
    write_init_py(output_dir, filenames)

    print(f"✅ Split complete. Created {len(filenames) + 1} files in '{output_dir}'.")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python umple_file_splitter.py <input_file> <output_dir>")
    else:
        split_umple_python_source_file(sys.argv[1], sys.argv[2])